<template>
  <div class="modal-backdrop">
    <div class="modal-card glass-panel export-modal animate-fade-in">
      <div class="modal-header">
        <div class="modal-icon-title">
          <Download class="modal-icon-download" />
          <h2>Export Schema</h2>
        </div>
        <button class="modal-close-btn" @click="$emit('close')">&times;</button>
      </div>

      <!-- Export tabs selector -->
      <div class="export-tabs">
        <button 
          v-for="tab in ['sql', 'json']" 
          :key="tab"
          class="export-tab-btn"
          :class="{ 'is-active': activeTab === tab }"
          @click="activeTab = tab"
        >
          {{ tab === 'sql' ? 'SQL Script (DDL)' : 'JSON Schema Backup' }}
        </button>
      </div>

      <div class="export-content">
        <!-- SQL Export Options -->
        <div v-if="activeTab === 'sql'" class="sql-options-group">
          <div class="dialect-selector-bar">
            <button 
              v-for="d in ['postgresql', 'mysql', 'sqlite']" 
              :key="d"
              class="dialect-btn"
              :class="{ 'is-active': sqlDialect === d }"
              @click="sqlDialect = d"
            >
              {{ d === 'postgresql' ? 'PostgreSQL' : d === 'mysql' ? 'MySQL' : 'SQLite' }}
            </button>
          </div>
          
          <div class="code-view-container">
            <pre class="code-view"><code>{{ compiledSQL }}</code></pre>
          </div>
          
          <div class="export-actions">
            <button class="btn btn-secondary" @click="copyToClipboard(compiledSQL)">
              <Copy class="btn-icon" /> Copy SQL
            </button>
            <button class="btn btn-primary" @click="downloadFile(compiledSQL, `${diagramName.replace(/\s+/g, '_')}_schema.sql`)">
              <Download class="btn-icon" /> Download SQL
            </button>
          </div>
        </div>

        <!-- JSON Export Options -->
        <div v-else class="json-options-group">
          <p class="json-notice">
            Export a full JSON blueprint of this diagram. You can import this JSON file back to restore tables, columns, and relations.
          </p>

          <div class="code-view-container">
            <pre class="code-view"><code>{{ compiledJSON }}</code></pre>
          </div>

          <div class="export-actions">
            <button class="btn btn-secondary" @click="copyToClipboard(compiledJSON)">
              <Copy class="btn-icon" /> Copy JSON
            </button>
            <button class="btn btn-primary" @click="downloadFile(compiledJSON, `${diagramName.replace(/\s+/g, '_')}_diagram.json`)">
              <Download class="btn-icon" /> Download Backup
            </button>
          </div>
        </div>
      </div>
      
      <div v-if="toastMessage" class="toast-popup">
        {{ toastMessage }}
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref, computed } from 'vue';
import { Download, Copy } from 'lucide-vue-next';

const props = defineProps({
  tables: { type: Array, required: true },
  columns: { type: Array, required: true },
  relations: { type: Array, required: true },
  dialect: { type: String, default: 'postgresql' },
  diagramName: { type: String, default: 'Untitled Schema' }
});

defineEmits(['close']);

const activeTab = ref('sql');
const sqlDialect = ref(props.dialect);
const toastMessage = ref('');

const showToast = (msg) => {
  toastMessage.value = msg;
  setTimeout(() => {
    toastMessage.value = '';
  }, 2000);
};

// Dialect SQL compilers
const compiledSQL = computed(() => {
  const tList = props.tables;
  const cList = props.columns;
  const rList = props.relations;
  const dia = sqlDialect.value;

  let sql = `-- SQL DDL Generated by SyncQL (by SynchronizeTeams)\n`;
  sql += `-- Schema Name: ${props.diagramName}\n`;
  sql += `-- Dialect: ${dia === 'postgresql' ? 'PostgreSQL' : dia === 'mysql' ? 'MySQL' : 'SQLite'}\n`;
  sql += `-- Created: ${new Date().toLocaleString()}\n\n`;

  // 1. If SQLite, compile relations directly INLINE inside CREATE TABLE
  if (dia === 'sqlite') {
    tList.forEach(t => {
      const tCols = cList.filter(c => c.table_id === t.id);
      sql += `CREATE TABLE \`${t.name}\` (\n`;
      
      const colDefs = tCols.map(c => {
        let def = `  \`${c.name}\` ${mapDataTypeSQLite(c.type, c.length)}`;
        
        if (c.is_primary) {
          def += ` PRIMARY KEY`;
          if (c.is_auto_increment) def += ` AUTOINCREMENT`;
        }
        if (!c.is_primary && !c.is_nullable) def += ` NOT NULL`;
        if (c.is_unique) def += ` UNIQUE`;
        if (c.default_value) def += ` DEFAULT ${c.default_value}`;
        
        return def;
      });

      // Find inline foreign keys for SQLite
      const inlineFKs = rList.filter(r => r.source_table_id === t.id);
      inlineFKs.forEach(r => {
        const sourceColName = cList.find(c => c.id === r.source_column_id)?.name;
        const targetTableName = tList.find(tb => tb.id === r.target_table_id)?.name;
        const targetColName = cList.find(c => c.id === r.target_column_id)?.name;
        
        if (sourceColName && targetTableName && targetColName) {
          colDefs.push(`  FOREIGN KEY (\`${sourceColName}\`) REFERENCES \`${targetTableName}\` (\`${targetColName}\`) ON DELETE ${r.on_delete} ON UPDATE ${r.on_update}`);
        }
      });

      sql += colDefs.join(',\n');
      sql += `\n);\n\n`;
    });
  } else if (dia === 'postgresql') {
    // Compile tables for Postgres
    tList.forEach(t => {
      const tCols = cList.filter(c => c.table_id === t.id);
      sql += `CREATE TABLE "${t.name}" (\n`;
      
      const colDefs = tCols.map(c => {
        let def = `  "${c.name}" `;
        
        if (c.is_primary && c.is_auto_increment) {
          def += `SERIAL PRIMARY KEY`;
        } else {
          def += mapDataTypePG(c.type, c.length);
          if (c.is_primary) def += ` PRIMARY KEY`;
          if (!c.is_primary && !c.is_nullable) def += ` NOT NULL`;
        }
        
        if (c.is_unique) def += ` UNIQUE`;
        if (c.default_value) def += ` DEFAULT ${c.default_value}`;
        
        return def;
      });

      sql += colDefs.join(',\n');
      sql += `\n);\n\n`;
      
      // Comments
      tCols.forEach(c => {
        if (c.comment) {
          sql += `COMMENT ON COLUMN "${t.name}"."${c.name}" IS '${c.comment.replace(/'/g, "''")}';\n`;
        }
      });
      if (tCols.some(c => c.comment)) sql += `\n`;
    });

    // Compile external foreign keys for Postgres
    rList.forEach(r => {
      const sourceTable = tList.find(t => t.id === r.source_table_id);
      const sourceCol = cList.find(c => c.id === r.source_column_id);
      const targetTable = tList.find(t => t.id === r.target_table_id);
      const targetCol = cList.find(c => c.id === r.target_column_id);

      if (sourceTable && sourceCol && targetTable && targetCol) {
        sql += `ALTER TABLE "${sourceTable.name}" ADD CONSTRAINT "fk_${sourceTable.name}_${sourceCol.name}" \n`;
        sql += `  FOREIGN KEY ("${sourceCol.name}") REFERENCES "${targetTable.name}" ("${targetCol.name}")\n`;
        sql += `  ON DELETE ${r.on_delete} ON UPDATE ${r.on_update};\n\n`;
      }
    });
  } else if (dia === 'mysql') {
    // Compile tables for MySQL
    tList.forEach(t => {
      const tCols = cList.filter(c => c.table_id === t.id);
      sql += `CREATE TABLE \`${t.name}\` (\n`;
      
      const colDefs = tCols.map(c => {
        let def = `  \`${c.name}\` ${mapDataTypeMySQL(c.type, c.length)}`;
        
        if (c.is_unsigned) def += ` UNSIGNED`;
        if (!c.is_nullable) def += ` NOT NULL`;
        if (c.is_auto_increment) def += ` AUTO_INCREMENT`;
        if (c.default_value) def += ` DEFAULT ${c.default_value}`;
        if (c.is_primary) def += ` PRIMARY KEY`;
        if (c.is_unique) def += ` UNIQUE`;
        if (c.comment) def += ` COMMENT '${c.comment.replace(/'/g, "\\'")}'`;
        
        return def;
      });

      sql += colDefs.join(',\n');
      sql += `\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;\n\n`;
    });

    // Compile external foreign keys for MySQL
    rList.forEach(r => {
      const sourceTable = tList.find(t => t.id === r.source_table_id);
      const sourceCol = cList.find(c => c.id === r.source_column_id);
      const targetTable = tList.find(t => t.id === r.target_table_id);
      const targetCol = cList.find(c => c.id === r.target_column_id);

      if (sourceTable && sourceCol && targetTable && targetCol) {
        sql += `ALTER TABLE \`${sourceTable.name}\` ADD CONSTRAINT \`fk_${sourceTable.name}_${sourceCol.name}\` \n`;
        sql += `  FOREIGN KEY (\`${sourceCol.name}\`) REFERENCES \`${targetTable.name}\` (\`${targetCol.name}\`)\n`;
        sql += `  ON DELETE ${r.on_delete} ON UPDATE ${r.on_update};\n\n`;
      }
    });
  }

  return sql;
});

const compiledJSON = computed(() => {
  const blueprint = {
    diagramName: props.diagramName,
    dialect: props.dialect,
    exportedAt: new Date().toISOString(),
    tables: props.tables,
    columns: props.columns,
    relations: props.relations
  };
  return JSON.stringify(blueprint, null, 2);
});

// Mapping Helper Functions
const mapDataTypeSQLite = (type, len) => {
  const t = type.toUpperCase();
  if (t === 'INT' || t === 'BIGINT' || t === 'TINYINT' || t === 'BOOLEAN') return 'INTEGER';
  if (t === 'VARCHAR' || t === 'TEXT' || t === 'UUID' || t === 'JSON') return 'TEXT';
  if (t === 'DECIMAL' || t === 'DOUBLE' || t === 'FLOAT') return 'REAL';
  return 'TEXT';
};

const mapDataTypePG = (type, len) => {
  const t = type.toUpperCase();
  if (t === 'INT') return 'INTEGER';
  if (t === 'VARCHAR') return `VARCHAR(${len || '255'})`;
  if (t === 'TEXT') return 'TEXT';
  if (t === 'BIGINT') return 'BIGINT';
  if (t === 'BOOLEAN') return 'BOOLEAN';
  if (t === 'DECIMAL') return `DECIMAL(${len || '10,2'})`;
  if (t === 'UUID') return 'UUID';
  if (t === 'JSON') return 'JSONB';
  return type;
};

const mapDataTypeMySQL = (type, len) => {
  const t = type.toUpperCase();
  if (t === 'INT') return 'INT';
  if (t === 'VARCHAR') return `VARCHAR(${len || '255'})`;
  if (t === 'TEXT') return 'TEXT';
  if (t === 'BIGINT') return 'BIGINT';
  if (t === 'BOOLEAN') return 'TINYINT(1)';
  if (t === 'DECIMAL') return `DECIMAL(${len || '10,2'})`;
  if (t === 'UUID') return 'VARCHAR(36)';
  if (t === 'JSON') return 'JSON';
  return type;
};

const copyToClipboard = (text) => {
  navigator.clipboard.writeText(text);
  showToast('Copied to clipboard!');
};

const downloadFile = (content, filename) => {
  const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
  showToast('Download started!');
};
</script>

<style scoped>
.export-modal {
  width: 780px !important;
  max-height: 85vh;
  display: flex;
  flex-direction: column;
  padding: 1.75rem 2rem !important;
}

.modal-icon-download {
  width: 22px;
  height: 22px;
  color: hsl(var(--primary));
}

/* Tabs selectors layout */
.export-tabs {
  display: flex;
  gap: 0.5rem;
  border-bottom: 1px solid hsl(var(--border));
  margin-bottom: 1.25rem;
  padding-bottom: 2px;
}

.export-tab-btn {
  background: transparent;
  border: none;
  color: hsl(var(--muted-foreground));
  font-size: 0.85rem;
  font-weight: 600;
  padding: 0.6rem 1rem;
  cursor: pointer;
  position: relative;
  transition: all 0.15s ease;
}

.export-tab-btn:hover {
  color: hsl(var(--foreground));
}

.export-tab-btn.is-active {
  color: hsl(var(--primary));
}

.export-tab-btn.is-active::after {
  content: '';
  position: absolute;
  bottom: -3px;
  left: 0;
  right: 0;
  height: 2px;
  background-color: hsl(var(--primary));
}

.export-content {
  flex: 1;
  display: flex;
  flex-direction: column;
  overflow: hidden;
}

/* SQL compiled dials and codeview structures */
.sql-options-group,
.json-options-group {
  height: 100%;
  display: flex;
  flex-direction: column;
  gap: 1rem;
  overflow: hidden;
}

.dialect-selector-bar {
  display: flex;
  gap: 0.5rem;
  background-color: hsl(var(--input));
  padding: 4px;
  border-radius: var(--radius-md);
  border: 1px solid hsl(var(--border));
  align-self: flex-start;
}

.dialect-btn {
  padding: 0.45rem 1rem;
  font-size: 0.775rem;
  font-weight: 600;
  color: hsl(var(--muted-foreground));
  background-color: transparent;
  border: none;
  cursor: pointer;
  border-radius: var(--radius-sm);
  transition: all 0.15s ease;
}

.dialect-btn.is-active {
  background-color: hsl(var(--card));
  color: #fff;
  box-shadow: 0 2px 4px rgba(0, 0, 0, 0.25);
}

.code-view-container {
  flex: 1;
  background-color: hsl(var(--input));
  border: 1px solid hsl(var(--border));
  border-radius: var(--radius-lg);
  padding: 1.25rem;
  overflow-y: auto;
  text-align: left;
}

.code-view {
  margin: 0;
  font-family: 'Courier New', Courier, monospace;
  font-size: 0.8rem;
  line-height: 1.5;
  color: #a8ffb2; /* Subtle terminal green color for readable syntax code */
  white-space: pre-wrap;
}

.json-notice {
  font-size: 0.825rem;
  color: hsl(var(--muted-foreground));
  margin: 0;
}

.export-actions {
  display: flex;
  justify-content: flex-end;
  gap: 0.75rem;
  border-top: 1px solid hsl(var(--border));
  padding-top: 1rem;
}

.btn-icon {
  width: 15px;
  height: 15px;
}

/* Sleek Toast notifications popup */
.toast-popup {
  position: absolute;
  bottom: 2rem;
  left: 50%;
  transform: translateX(-50%);
  background-color: hsl(var(--primary));
  color: #fff;
  font-size: 0.8rem;
  font-weight: 600;
  padding: 0.5rem 1.25rem;
  border-radius: var(--radius-xl);
  box-shadow: 0 4px 12px rgba(0, 0, 0, 0.35);
  animation: fadeInToast 0.2s cubic-bezier(0.16, 1, 0.3, 1) forwards;
}

@keyframes fadeInToast {
  from { opacity: 0; transform: translate(-50%, 10px); }
  to { opacity: 1; transform: translate(-50%, 0); }
}
</style>
